apiVersion: v1
kind: Pod
metadata:
  name: airflow-deployment-f8c7b767b-trhgv
  labels:
    purpose: changing-env-var
spec:
  containers:
  - name: airflow 
    image: puckel/docker-airflow
    env:
    - name: LOAD_EX
      value: "y"
