apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  labels:
    app: superset
spec:
  selector:
    matchLabels:
      app: superset
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: amancevice/superset
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
