apiVersion: v1
kind: Service
metadata:
  labels:
    app: superset
  name: superset
  namespace: default
spec:
  ports:
  - nodePort: 31557
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: superset
  type: NodePort