apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-01-12T21:15:54Z"
  generation: 1
  labels:
    app: airflow
  name: airflow
  namespace: default
  resourceVersion: "27068"
  uid: ddb8cd96-f10b-4142-a6f3-14dc9ce524bb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: airflow
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: airflow
    spec:
      containers:
      - image: puckel/docker-airflow
        imagePullPolicy: Always
        name: docker-airflow
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-12T21:17:07Z"
    lastUpdateTime: "2022-01-12T21:17:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-12T21:15:54Z"
    lastUpdateTime: "2022-01-12T21:17:07Z"
    message: ReplicaSet "airflow-65745c5c57" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
