---
- name: copy hostname file
  template:
     src: templates/hostname.j2
     dest: /tmp/test2

- name: Display test2 contents
  command: cat /tmp/test2
  register: command_output

- name: print to console
  debug:
    msg: "{{command_output.stdout}}"
