pipeline {
    agent {
        label 'agent_1'}
            stages {
                stage('cd to folder') {
                    steps {
                        sh '''#!/bin/bash
                        cd /external/projects/DevOpsExperts/Lesson-6/web-and-automation-solutions/selenium/docker
                        python simple_selenium.py
                        '''
                    }
                }
        }
}