apiVersion: v1
data:
  LOAD_EX: "y"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-12T23:55:12Z"
  name: env-config-airflow
  namespace: default
  resourceVersion: "33819"
  uid: 0d2c12dd-1f75-409e-af0d-572765675368
