apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-01-12T22:16:02Z"
  labels:
    app: airflow
  name: airflow
  namespace: default
  resourceVersion: "29569"
  uid: 63107866-e956-43e1-9800-6b62c67ec35b
spec:
  clusterIP: 10.97.27.74
  clusterIPs:
  - 10.97.27.74
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30143
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: airflow
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
